2021-05-28 06:00:55,399 INFO    MainThread:29752 [wandb_setup.py:_flush():69] setting env: {}
2021-05-28 06:00:55,399 INFO    MainThread:29752 [wandb_setup.py:_flush():69] setting login settings: {}
2021-05-28 06:00:55,400 INFO    MainThread:29752 [wandb_init.py:_log_setup():336] Logging user logs to /opt/ml/gitclone/p4-mod-model_diet/wandb/run-20210528_060055-1mexr2al/logs/debug.log
2021-05-28 06:00:55,400 INFO    MainThread:29752 [wandb_init.py:_log_setup():337] Logging internal logs to /opt/ml/gitclone/p4-mod-model_diet/wandb/run-20210528_060055-1mexr2al/logs/debug-internal.log
2021-05-28 06:00:55,400 INFO    MainThread:29752 [wandb_init.py:init():369] calling init triggers
2021-05-28 06:00:55,400 INFO    MainThread:29752 [wandb_init.py:init():374] wandb.init called with sweep_config: {}
config: {'img_size': 160, 'batch_size': 8, 'init_lr': 0.0001543133165444431}
2021-05-28 06:00:55,400 INFO    MainThread:29752 [wandb_init.py:init():389] re-initializing run, found existing run on stack: 263xtlvv
2021-05-28 06:00:55,400 INFO    MainThread:29752 [wandb_run.py:finish():1208] finishing run seokjin/optuna/263xtlvv
2021-05-28 06:00:55,400 INFO    MainThread:29752 [wandb_run.py:_atexit_cleanup():1535] got exitcode: 0
2021-05-28 06:00:55,401 INFO    MainThread:29752 [wandb_run.py:_restore():1507] restore
2021-05-28 06:00:57,601 INFO    MainThread:29752 [wandb_run.py:_wait_for_finish():1657] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 717
  total_bytes: 717
}

2021-05-28 06:00:57,766 INFO    MainThread:29752 [wandb_run.py:_wait_for_finish():1657] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 717
  total_bytes: 4221
}

2021-05-28 06:00:58,164 INFO    MainThread:29752 [wandb_run.py:_wait_for_finish():1657] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 1365
  total_bytes: 4221
}

2021-05-28 06:00:58,266 INFO    MainThread:29752 [wandb_run.py:_wait_for_finish():1657] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 1365
  total_bytes: 4221
}

2021-05-28 06:00:58,368 INFO    MainThread:29752 [wandb_run.py:_wait_for_finish():1657] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 4221
  total_bytes: 4221
}

2021-05-28 06:00:58,469 INFO    MainThread:29752 [wandb_run.py:_wait_for_finish():1657] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 4221
  total_bytes: 4221
}

2021-05-28 06:00:58,571 INFO    MainThread:29752 [wandb_run.py:_wait_for_finish():1657] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 4221
  total_bytes: 4221
}

2021-05-28 06:00:58,672 INFO    MainThread:29752 [wandb_run.py:_wait_for_finish():1657] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 4221
  total_bytes: 4221
}

2021-05-28 06:00:58,774 INFO    MainThread:29752 [wandb_run.py:_wait_for_finish():1657] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 4221
  total_bytes: 4221
}

2021-05-28 06:00:58,876 INFO    MainThread:29752 [wandb_run.py:_wait_for_finish():1657] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 4221
  total_bytes: 4221
}

2021-05-28 06:00:58,977 INFO    MainThread:29752 [wandb_run.py:_wait_for_finish():1657] got exit ret: done: true
exit_result {
}
file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 4221
  total_bytes: 4221
}

2021-05-28 06:01:00,072 INFO    MainThread:29752 [wandb_run.py:_show_summary():1812] rendering summary
2021-05-28 06:01:00,072 INFO    MainThread:29752 [wandb_run.py:_show_history():1850] rendering history
2021-05-28 06:01:00,073 INFO    MainThread:29752 [wandb_run.py:_show_files():1879] logging synced files
2021-05-28 06:01:00,075 INFO    MainThread:29752 [wandb_init.py:init():418] starting backend
2021-05-28 06:01:00,075 INFO    MainThread:29752 [backend.py:_multiprocessing_setup():70] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2021-05-28 06:01:00,078 INFO    MainThread:29752 [backend.py:ensure_launched():132] starting backend process...
2021-05-28 06:01:00,130 INFO    MainThread:29752 [backend.py:ensure_launched():136] started backend process with pid: 31202
2021-05-28 06:01:00,135 INFO    MainThread:29752 [wandb_init.py:init():423] backend started and connected
2021-05-28 06:01:00,137 INFO    MainThread:29752 [wandb_init.py:init():465] updated telemetry
2021-05-28 06:01:00,137 INFO    MainThread:29752 [wandb_init.py:init():484] communicating current version
2021-05-28 06:01:00,916 INFO    MainThread:29752 [wandb_init.py:init():489] got version response upgrade_message: "wandb version 0.10.31 is available!  To upgrade, please run:\n $ pip install wandb --upgrade"

2021-05-28 06:01:00,918 INFO    MainThread:29752 [wandb_init.py:init():497] communicating run to backend with 30 second timeout
2021-05-28 06:01:01,136 INFO    MainThread:29752 [wandb_init.py:init():522] starting run threads in backend
2021-05-28 06:01:01,176 INFO    MainThread:29752 [wandb_run.py:_console_start():1565] atexit reg
2021-05-28 06:01:01,176 INFO    MainThread:29752 [wandb_run.py:_redirect():1412] redirect: SettingsConsole.REDIRECT
2021-05-28 06:01:01,176 INFO    MainThread:29752 [wandb_run.py:_redirect():1417] Redirecting console.
2021-05-28 06:01:01,178 INFO    MainThread:29752 [wandb_run.py:_redirect():1479] Redirects installed.
2021-05-28 06:01:01,178 INFO    MainThread:29752 [wandb_init.py:init():546] run started, returning control to user process
2021-05-28 06:12:29,165 INFO    MainThread:29752 [wandb_setup.py:_flush():69] setting env: {}
2021-05-28 06:12:29,165 INFO    MainThread:29752 [wandb_setup.py:_flush():69] setting login settings: {}
2021-05-28 06:12:29,165 INFO    MainThread:29752 [wandb_init.py:_log_setup():336] Logging user logs to /opt/ml/gitclone/p4-mod-model_diet/wandb/run-20210528_061229-1xslthma/logs/debug.log
2021-05-28 06:12:29,165 INFO    MainThread:29752 [wandb_init.py:_log_setup():337] Logging internal logs to /opt/ml/gitclone/p4-mod-model_diet/wandb/run-20210528_061229-1xslthma/logs/debug-internal.log
2021-05-28 06:12:29,165 INFO    MainThread:29752 [wandb_init.py:init():369] calling init triggers
2021-05-28 06:12:29,165 INFO    MainThread:29752 [wandb_init.py:init():374] wandb.init called with sweep_config: {}
config: {'img_size': 384, 'batch_size': 16, 'init_lr': 0.0015378039139879267}
2021-05-28 06:12:29,165 INFO    MainThread:29752 [wandb_init.py:init():389] re-initializing run, found existing run on stack: 1mexr2al
2021-05-28 06:12:29,165 INFO    MainThread:29752 [wandb_run.py:finish():1208] finishing run seokjin/optuna/1mexr2al
