2021-05-28 03:58:58,918 INFO    MainThread:28799 [wandb_setup.py:_flush():69] setting env: {}
2021-05-28 03:58:58,918 INFO    MainThread:28799 [wandb_setup.py:_flush():69] setting login settings: {}
2021-05-28 03:58:58,918 INFO    MainThread:28799 [wandb_init.py:_log_setup():336] Logging user logs to /opt/ml/gitclone/p4-mod-model_diet/wandb/run-20210528_035858-1uuc3tne/logs/debug.log
2021-05-28 03:58:58,918 INFO    MainThread:28799 [wandb_init.py:_log_setup():337] Logging internal logs to /opt/ml/gitclone/p4-mod-model_diet/wandb/run-20210528_035858-1uuc3tne/logs/debug-internal.log
2021-05-28 03:58:58,918 INFO    MainThread:28799 [wandb_init.py:init():369] calling init triggers
2021-05-28 03:58:58,918 INFO    MainThread:28799 [wandb_init.py:init():374] wandb.init called with sweep_config: {}
config: {'img_size': 2, 'batch_size': 16, 'init_lr': 0.0007790872098054555}
2021-05-28 03:58:58,918 INFO    MainThread:28799 [wandb_init.py:init():418] starting backend
2021-05-28 03:58:58,918 INFO    MainThread:28799 [backend.py:_multiprocessing_setup():70] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2021-05-28 03:58:58,929 INFO    MainThread:28799 [backend.py:ensure_launched():132] starting backend process...
2021-05-28 03:58:58,934 INFO    MainThread:28799 [backend.py:ensure_launched():136] started backend process with pid: 28808
2021-05-28 03:58:58,935 INFO    MainThread:28799 [wandb_init.py:init():423] backend started and connected
2021-05-28 03:58:58,937 INFO    MainThread:28799 [wandb_init.py:init():465] updated telemetry
2021-05-28 03:58:58,937 INFO    MainThread:28799 [wandb_init.py:init():484] communicating current version
2021-05-28 03:58:59,733 INFO    MainThread:28799 [wandb_init.py:init():489] got version response upgrade_message: "wandb version 0.10.31 is available!  To upgrade, please run:\n $ pip install wandb --upgrade"

2021-05-28 03:58:59,734 INFO    MainThread:28799 [wandb_init.py:init():497] communicating run to backend with 30 second timeout
2021-05-28 03:58:59,950 INFO    MainThread:28799 [wandb_init.py:init():522] starting run threads in backend
2021-05-28 03:58:59,987 INFO    MainThread:28799 [wandb_run.py:_console_start():1565] atexit reg
2021-05-28 03:58:59,987 INFO    MainThread:28799 [wandb_run.py:_redirect():1412] redirect: SettingsConsole.REDIRECT
2021-05-28 03:58:59,988 INFO    MainThread:28799 [wandb_run.py:_redirect():1417] Redirecting console.
2021-05-28 03:58:59,992 INFO    MainThread:28799 [wandb_run.py:_redirect():1479] Redirects installed.
2021-05-28 03:58:59,992 INFO    MainThread:28799 [wandb_init.py:init():546] run started, returning control to user process
2021-05-28 03:58:59,996 INFO    MainThread:28799 [wandb_run.py:_atexit_cleanup():1535] got exitcode: 1
2021-05-28 03:58:59,996 INFO    MainThread:28799 [wandb_run.py:_restore():1507] restore
2021-05-28 03:59:02,003 INFO    MainThread:28799 [wandb_run.py:_wait_for_finish():1657] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 717
  total_bytes: 717
}

2021-05-28 03:59:02,320 INFO    MainThread:28799 [wandb_run.py:_wait_for_finish():1657] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 717
  total_bytes: 717
}

2021-05-28 03:59:02,963 INFO    MainThread:28799 [wandb_run.py:_wait_for_finish():1657] got exit ret: file_counts {
  wandb_count: 4
}
pusher_stats {
  uploaded_bytes: 717
  total_bytes: 3858
}

2021-05-28 03:59:03,348 INFO    MainThread:28799 [wandb_run.py:_wait_for_finish():1657] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 3444
  total_bytes: 3860
}

2021-05-28 03:59:03,450 INFO    MainThread:28799 [wandb_run.py:_wait_for_finish():1657] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 3860
  total_bytes: 3860
}

2021-05-28 03:59:03,552 INFO    MainThread:28799 [wandb_run.py:_wait_for_finish():1657] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 3860
  total_bytes: 3860
}

2021-05-28 03:59:03,653 INFO    MainThread:28799 [wandb_run.py:_wait_for_finish():1657] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 3860
  total_bytes: 3860
}

2021-05-28 03:59:03,755 INFO    MainThread:28799 [wandb_run.py:_wait_for_finish():1657] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 3860
  total_bytes: 3860
}

2021-05-28 03:59:03,856 INFO    MainThread:28799 [wandb_run.py:_wait_for_finish():1657] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 3860
  total_bytes: 3860
}

2021-05-28 03:59:03,958 INFO    MainThread:28799 [wandb_run.py:_wait_for_finish():1657] got exit ret: done: true
exit_result {
}
file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 3860
  total_bytes: 3860
}

2021-05-28 03:59:05,042 INFO    MainThread:28799 [wandb_run.py:_show_files():1879] logging synced files
