2021-05-28 04:09:40,888 INFO    MainThread:29021 [wandb_setup.py:_flush():69] setting env: {}
2021-05-28 04:09:40,888 INFO    MainThread:29021 [wandb_setup.py:_flush():69] setting login settings: {}
2021-05-28 04:09:40,888 INFO    MainThread:29021 [wandb_init.py:_log_setup():336] Logging user logs to /opt/ml/gitclone/p4-mod-model_diet/wandb/run-20210528_040940-3r8wcpdq/logs/debug.log
2021-05-28 04:09:40,888 INFO    MainThread:29021 [wandb_init.py:_log_setup():337] Logging internal logs to /opt/ml/gitclone/p4-mod-model_diet/wandb/run-20210528_040940-3r8wcpdq/logs/debug-internal.log
2021-05-28 04:09:40,888 INFO    MainThread:29021 [wandb_init.py:init():369] calling init triggers
2021-05-28 04:09:40,888 INFO    MainThread:29021 [wandb_init.py:init():374] wandb.init called with sweep_config: {}
config: {'img_size': 1, 'batch_size': 8, 'init_lr': 0.009398919758996802}
2021-05-28 04:09:40,888 INFO    MainThread:29021 [wandb_init.py:init():418] starting backend
2021-05-28 04:09:40,888 INFO    MainThread:29021 [backend.py:_multiprocessing_setup():70] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2021-05-28 04:09:40,896 INFO    MainThread:29021 [backend.py:ensure_launched():132] starting backend process...
2021-05-28 04:09:40,900 INFO    MainThread:29021 [backend.py:ensure_launched():136] started backend process with pid: 29030
2021-05-28 04:09:40,902 INFO    MainThread:29021 [wandb_init.py:init():423] backend started and connected
2021-05-28 04:09:40,903 INFO    MainThread:29021 [wandb_init.py:init():465] updated telemetry
2021-05-28 04:09:40,904 INFO    MainThread:29021 [wandb_init.py:init():484] communicating current version
2021-05-28 04:09:42,105 INFO    MainThread:29021 [wandb_init.py:init():489] got version response upgrade_message: "wandb version 0.10.31 is available!  To upgrade, please run:\n $ pip install wandb --upgrade"

2021-05-28 04:09:42,107 INFO    MainThread:29021 [wandb_init.py:init():497] communicating run to backend with 30 second timeout
2021-05-28 04:09:42,340 INFO    MainThread:29021 [wandb_init.py:init():522] starting run threads in backend
2021-05-28 04:09:42,377 INFO    MainThread:29021 [wandb_run.py:_console_start():1565] atexit reg
2021-05-28 04:09:42,377 INFO    MainThread:29021 [wandb_run.py:_redirect():1412] redirect: SettingsConsole.REDIRECT
2021-05-28 04:09:42,378 INFO    MainThread:29021 [wandb_run.py:_redirect():1417] Redirecting console.
2021-05-28 04:09:42,380 INFO    MainThread:29021 [wandb_run.py:_redirect():1479] Redirects installed.
2021-05-28 04:09:42,380 INFO    MainThread:29021 [wandb_init.py:init():546] run started, returning control to user process
2021-05-28 04:14:28,099 INFO    MainThread:29021 [wandb_run.py:_atexit_cleanup():1535] got exitcode: 1
2021-05-28 04:14:28,099 INFO    MainThread:29021 [wandb_run.py:_restore():1507] restore
2021-05-28 04:14:30,106 INFO    MainThread:29021 [wandb_run.py:_wait_for_finish():1657] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 717
  total_bytes: 717
}

2021-05-28 04:14:30,328 INFO    MainThread:29021 [wandb_run.py:_wait_for_finish():1657] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 717
  total_bytes: 717
}

2021-05-28 04:14:30,447 INFO    MainThread:29021 [wandb_run.py:_wait_for_finish():1657] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 717
  total_bytes: 3833
}

2021-05-28 04:14:30,932 INFO    MainThread:29021 [wandb_run.py:_wait_for_finish():1657] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 3833
  total_bytes: 3833
}

2021-05-28 04:14:31,034 INFO    MainThread:29021 [wandb_run.py:_wait_for_finish():1657] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 3833
  total_bytes: 3833
}

2021-05-28 04:14:31,135 INFO    MainThread:29021 [wandb_run.py:_wait_for_finish():1657] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 3833
  total_bytes: 3833
}

2021-05-28 04:14:31,236 INFO    MainThread:29021 [wandb_run.py:_wait_for_finish():1657] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 3833
  total_bytes: 3833
}

2021-05-28 04:14:31,338 INFO    MainThread:29021 [wandb_run.py:_wait_for_finish():1657] got exit ret: done: true
exit_result {
}
file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 3833
  total_bytes: 3833
}

2021-05-28 04:14:32,417 INFO    MainThread:29021 [wandb_run.py:_show_files():1879] logging synced files
