2021-05-28 07:20:32,352 INFO    MainThread:29752 [wandb_setup.py:_flush():69] setting env: {}
2021-05-28 07:20:32,352 INFO    MainThread:29752 [wandb_setup.py:_flush():69] setting login settings: {}
2021-05-28 07:20:32,352 INFO    MainThread:29752 [wandb_init.py:_log_setup():336] Logging user logs to /opt/ml/gitclone/p4-mod-model_diet/wandb/run-20210528_072032-2cmlsf6p/logs/debug.log
2021-05-28 07:20:32,352 INFO    MainThread:29752 [wandb_init.py:_log_setup():337] Logging internal logs to /opt/ml/gitclone/p4-mod-model_diet/wandb/run-20210528_072032-2cmlsf6p/logs/debug-internal.log
2021-05-28 07:20:32,353 INFO    MainThread:29752 [wandb_init.py:init():369] calling init triggers
2021-05-28 07:20:32,353 INFO    MainThread:29752 [wandb_init.py:init():374] wandb.init called with sweep_config: {}
config: {'img_size': 224, 'batch_size': 64, 'init_lr': 0.00043079393349890015}
2021-05-28 07:20:32,353 INFO    MainThread:29752 [wandb_init.py:init():389] re-initializing run, found existing run on stack: 2rx02r7a
2021-05-28 07:20:32,353 INFO    MainThread:29752 [wandb_run.py:finish():1208] finishing run seokjin/optuna/2rx02r7a
2021-05-28 07:20:32,353 INFO    MainThread:29752 [wandb_run.py:_atexit_cleanup():1535] got exitcode: 0
2021-05-28 07:20:32,353 INFO    MainThread:29752 [wandb_run.py:_restore():1507] restore
2021-05-28 07:20:34,362 INFO    MainThread:29752 [wandb_run.py:_wait_for_finish():1657] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 717
  total_bytes: 717
}

2021-05-28 07:20:34,592 INFO    MainThread:29752 [wandb_run.py:_wait_for_finish():1657] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 717
  total_bytes: 717
}

2021-05-28 07:20:35,288 INFO    MainThread:29752 [wandb_run.py:_wait_for_finish():1657] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 717
  total_bytes: 4228
}

2021-05-28 07:20:35,808 INFO    MainThread:29752 [wandb_run.py:_wait_for_finish():1657] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 4228
  total_bytes: 4228
}

2021-05-28 07:20:35,909 INFO    MainThread:29752 [wandb_run.py:_wait_for_finish():1657] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 4228
  total_bytes: 4228
}

2021-05-28 07:20:36,011 INFO    MainThread:29752 [wandb_run.py:_wait_for_finish():1657] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 4228
  total_bytes: 4228
}

2021-05-28 07:20:36,112 INFO    MainThread:29752 [wandb_run.py:_wait_for_finish():1657] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 4228
  total_bytes: 4228
}

2021-05-28 07:20:36,213 INFO    MainThread:29752 [wandb_run.py:_wait_for_finish():1657] got exit ret: done: true
exit_result {
}
file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 4228
  total_bytes: 4228
}

2021-05-28 07:20:37,311 INFO    MainThread:29752 [wandb_run.py:_show_summary():1812] rendering summary
2021-05-28 07:20:37,313 INFO    MainThread:29752 [wandb_run.py:_show_history():1850] rendering history
2021-05-28 07:20:37,313 INFO    MainThread:29752 [wandb_run.py:_show_files():1879] logging synced files
2021-05-28 07:20:37,316 INFO    MainThread:29752 [wandb_init.py:init():418] starting backend
2021-05-28 07:20:37,316 INFO    MainThread:29752 [backend.py:_multiprocessing_setup():70] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2021-05-28 07:20:37,319 INFO    MainThread:29752 [backend.py:ensure_launched():132] starting backend process...
2021-05-28 07:20:37,365 INFO    MainThread:29752 [backend.py:ensure_launched():136] started backend process with pid: 455
2021-05-28 07:20:37,367 INFO    MainThread:29752 [wandb_init.py:init():423] backend started and connected
2021-05-28 07:20:37,368 INFO    MainThread:29752 [wandb_init.py:init():465] updated telemetry
2021-05-28 07:20:37,369 INFO    MainThread:29752 [wandb_init.py:init():484] communicating current version
2021-05-28 07:20:38,549 INFO    MainThread:29752 [wandb_init.py:init():489] got version response upgrade_message: "wandb version 0.10.31 is available!  To upgrade, please run:\n $ pip install wandb --upgrade"

2021-05-28 07:20:38,549 INFO    MainThread:29752 [wandb_init.py:init():497] communicating run to backend with 30 second timeout
2021-05-28 07:20:38,773 INFO    MainThread:29752 [wandb_init.py:init():522] starting run threads in backend
2021-05-28 07:20:38,811 INFO    MainThread:29752 [wandb_run.py:_console_start():1565] atexit reg
2021-05-28 07:20:38,811 INFO    MainThread:29752 [wandb_run.py:_redirect():1412] redirect: SettingsConsole.REDIRECT
2021-05-28 07:20:38,811 INFO    MainThread:29752 [wandb_run.py:_redirect():1417] Redirecting console.
2021-05-28 07:20:38,813 INFO    MainThread:29752 [wandb_run.py:_redirect():1479] Redirects installed.
2021-05-28 07:20:38,813 INFO    MainThread:29752 [wandb_init.py:init():546] run started, returning control to user process
2021-05-28 07:31:49,349 INFO    MainThread:29752 [wandb_setup.py:_flush():69] setting env: {}
2021-05-28 07:31:49,349 INFO    MainThread:29752 [wandb_setup.py:_flush():69] setting login settings: {}
2021-05-28 07:31:49,349 INFO    MainThread:29752 [wandb_init.py:_log_setup():336] Logging user logs to /opt/ml/gitclone/p4-mod-model_diet/wandb/run-20210528_073149-1d1ii72e/logs/debug.log
2021-05-28 07:31:49,350 INFO    MainThread:29752 [wandb_init.py:_log_setup():337] Logging internal logs to /opt/ml/gitclone/p4-mod-model_diet/wandb/run-20210528_073149-1d1ii72e/logs/debug-internal.log
2021-05-28 07:31:49,350 INFO    MainThread:29752 [wandb_init.py:init():369] calling init triggers
2021-05-28 07:31:49,350 INFO    MainThread:29752 [wandb_init.py:init():374] wandb.init called with sweep_config: {}
config: {'img_size': 160, 'batch_size': 64, 'init_lr': 0.0003748777528284667}
2021-05-28 07:31:49,350 INFO    MainThread:29752 [wandb_init.py:init():389] re-initializing run, found existing run on stack: 2cmlsf6p
2021-05-28 07:31:49,350 INFO    MainThread:29752 [wandb_run.py:finish():1208] finishing run seokjin/optuna/2cmlsf6p
