2021-05-28 04:15:47,909 INFO    MainThread:29160 [wandb_setup.py:_flush():69] setting env: {}
2021-05-28 04:15:47,909 INFO    MainThread:29160 [wandb_setup.py:_flush():69] setting login settings: {}
2021-05-28 04:15:47,909 INFO    MainThread:29160 [wandb_init.py:_log_setup():336] Logging user logs to /opt/ml/gitclone/p4-mod-model_diet/wandb/run-20210528_041547-21o7x5e6/logs/debug.log
2021-05-28 04:15:47,909 INFO    MainThread:29160 [wandb_init.py:_log_setup():337] Logging internal logs to /opt/ml/gitclone/p4-mod-model_diet/wandb/run-20210528_041547-21o7x5e6/logs/debug-internal.log
2021-05-28 04:15:47,910 INFO    MainThread:29160 [wandb_init.py:init():369] calling init triggers
2021-05-28 04:15:47,910 INFO    MainThread:29160 [wandb_init.py:init():374] wandb.init called with sweep_config: {}
config: {'img_size': 1, 'batch_size': 64, 'init_lr': 0.0004359148976251259}
2021-05-28 04:15:47,910 INFO    MainThread:29160 [wandb_init.py:init():418] starting backend
2021-05-28 04:15:47,910 INFO    MainThread:29160 [backend.py:_multiprocessing_setup():70] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2021-05-28 04:15:47,920 INFO    MainThread:29160 [backend.py:ensure_launched():132] starting backend process...
2021-05-28 04:15:47,926 INFO    MainThread:29160 [backend.py:ensure_launched():136] started backend process with pid: 29169
2021-05-28 04:15:47,928 INFO    MainThread:29160 [wandb_init.py:init():423] backend started and connected
2021-05-28 04:15:47,930 INFO    MainThread:29160 [wandb_init.py:init():465] updated telemetry
2021-05-28 04:15:47,930 INFO    MainThread:29160 [wandb_init.py:init():484] communicating current version
2021-05-28 04:15:48,677 INFO    MainThread:29160 [wandb_init.py:init():489] got version response upgrade_message: "wandb version 0.10.31 is available!  To upgrade, please run:\n $ pip install wandb --upgrade"

2021-05-28 04:15:48,678 INFO    MainThread:29160 [wandb_init.py:init():497] communicating run to backend with 30 second timeout
2021-05-28 04:15:48,897 INFO    MainThread:29160 [wandb_init.py:init():522] starting run threads in backend
2021-05-28 04:15:48,935 INFO    MainThread:29160 [wandb_run.py:_console_start():1565] atexit reg
2021-05-28 04:15:48,936 INFO    MainThread:29160 [wandb_run.py:_redirect():1412] redirect: SettingsConsole.REDIRECT
2021-05-28 04:15:48,936 INFO    MainThread:29160 [wandb_run.py:_redirect():1417] Redirecting console.
2021-05-28 04:15:48,938 INFO    MainThread:29160 [wandb_run.py:_redirect():1479] Redirects installed.
2021-05-28 04:15:48,938 INFO    MainThread:29160 [wandb_init.py:init():546] run started, returning control to user process
2021-05-28 04:18:44,051 INFO    MainThread:29160 [wandb_run.py:_atexit_cleanup():1535] got exitcode: 1
2021-05-28 04:18:44,052 INFO    MainThread:29160 [wandb_run.py:_restore():1507] restore
2021-05-28 04:18:46,250 INFO    MainThread:29160 [wandb_run.py:_wait_for_finish():1657] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 717
  total_bytes: 717
}

2021-05-28 04:18:46,358 INFO    MainThread:29160 [wandb_run.py:_wait_for_finish():1657] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 717
  total_bytes: 717
}

2021-05-28 04:18:46,947 INFO    MainThread:29160 [wandb_run.py:_wait_for_finish():1657] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 717
  total_bytes: 3850
}

2021-05-28 04:18:47,329 INFO    MainThread:29160 [wandb_run.py:_wait_for_finish():1657] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 3850
  total_bytes: 3850
}

2021-05-28 04:18:47,430 INFO    MainThread:29160 [wandb_run.py:_wait_for_finish():1657] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 3850
  total_bytes: 3850
}

2021-05-28 04:18:47,532 INFO    MainThread:29160 [wandb_run.py:_wait_for_finish():1657] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 3850
  total_bytes: 3850
}

2021-05-28 04:18:47,633 INFO    MainThread:29160 [wandb_run.py:_wait_for_finish():1657] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 3850
  total_bytes: 3850
}

2021-05-28 04:18:47,734 INFO    MainThread:29160 [wandb_run.py:_wait_for_finish():1657] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 3850
  total_bytes: 3850
}

2021-05-28 04:18:47,835 INFO    MainThread:29160 [wandb_run.py:_wait_for_finish():1657] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 3850
  total_bytes: 3850
}

2021-05-28 04:18:47,936 INFO    MainThread:29160 [wandb_run.py:_wait_for_finish():1657] got exit ret: done: true
exit_result {
}
file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 3850
  total_bytes: 3850
}

2021-05-28 04:18:49,018 INFO    MainThread:29160 [wandb_run.py:_show_files():1879] logging synced files
