2021-05-28 00:11:06,387 INFO    MainThread:23026 [wandb_setup.py:_flush():69] setting env: {}
2021-05-28 00:11:06,388 INFO    MainThread:23026 [wandb_setup.py:_flush():69] setting login settings: {}
2021-05-28 00:11:06,388 INFO    MainThread:23026 [wandb_init.py:_log_setup():336] Logging user logs to /opt/ml/gitclone/p4-mod-model_diet/wandb/run-20210528_001106-vgxoqvhz/logs/debug.log
2021-05-28 00:11:06,388 INFO    MainThread:23026 [wandb_init.py:_log_setup():337] Logging internal logs to /opt/ml/gitclone/p4-mod-model_diet/wandb/run-20210528_001106-vgxoqvhz/logs/debug-internal.log
2021-05-28 00:11:06,388 INFO    MainThread:23026 [wandb_init.py:init():369] calling init triggers
2021-05-28 00:11:06,388 INFO    MainThread:23026 [wandb_init.py:init():374] wandb.init called with sweep_config: {}
config: {'img_size': 4, 'batch_size': 64, 'init_lr': 0.00032323627253588884}
2021-05-28 00:11:06,388 INFO    MainThread:23026 [wandb_init.py:init():418] starting backend
2021-05-28 00:11:06,388 INFO    MainThread:23026 [backend.py:_multiprocessing_setup():70] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2021-05-28 00:11:06,398 INFO    MainThread:23026 [backend.py:ensure_launched():132] starting backend process...
2021-05-28 00:11:06,406 INFO    MainThread:23026 [backend.py:ensure_launched():136] started backend process with pid: 23035
2021-05-28 00:11:06,408 INFO    MainThread:23026 [wandb_init.py:init():423] backend started and connected
2021-05-28 00:11:06,409 INFO    MainThread:23026 [wandb_init.py:init():465] updated telemetry
2021-05-28 00:11:06,410 INFO    MainThread:23026 [wandb_init.py:init():484] communicating current version
2021-05-28 00:11:07,581 INFO    MainThread:23026 [wandb_init.py:init():489] got version response upgrade_message: "wandb version 0.10.31 is available!  To upgrade, please run:\n $ pip install wandb --upgrade"

2021-05-28 00:11:07,581 INFO    MainThread:23026 [wandb_init.py:init():497] communicating run to backend with 30 second timeout
2021-05-28 00:11:07,809 INFO    MainThread:23026 [wandb_init.py:init():522] starting run threads in backend
2021-05-28 00:11:07,850 INFO    MainThread:23026 [wandb_run.py:_console_start():1565] atexit reg
2021-05-28 00:11:07,851 INFO    MainThread:23026 [wandb_run.py:_redirect():1412] redirect: SettingsConsole.REDIRECT
2021-05-28 00:11:07,851 INFO    MainThread:23026 [wandb_run.py:_redirect():1417] Redirecting console.
2021-05-28 00:11:07,853 INFO    MainThread:23026 [wandb_run.py:_redirect():1479] Redirects installed.
2021-05-28 00:11:07,853 INFO    MainThread:23026 [wandb_init.py:init():546] run started, returning control to user process
2021-05-28 00:14:02,200 INFO    MainThread:23026 [wandb_run.py:_atexit_cleanup():1535] got exitcode: 1
2021-05-28 00:14:02,203 INFO    MainThread:23026 [wandb_run.py:_restore():1507] restore
2021-05-28 00:14:04,211 INFO    MainThread:23026 [wandb_run.py:_wait_for_finish():1657] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 717
  total_bytes: 717
}

2021-05-28 00:14:04,477 INFO    MainThread:23026 [wandb_run.py:_wait_for_finish():1657] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 717
  total_bytes: 717
}

2021-05-28 00:14:04,904 INFO    MainThread:23026 [wandb_run.py:_wait_for_finish():1657] got exit ret: file_counts {
  wandb_count: 4
}
pusher_stats {
  uploaded_bytes: 717
  total_bytes: 3843
}

2021-05-28 00:14:05,294 INFO    MainThread:23026 [wandb_run.py:_wait_for_finish():1657] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 3845
  total_bytes: 3845
}

2021-05-28 00:14:05,396 INFO    MainThread:23026 [wandb_run.py:_wait_for_finish():1657] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 3845
  total_bytes: 3845
}

2021-05-28 00:14:05,497 INFO    MainThread:23026 [wandb_run.py:_wait_for_finish():1657] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 3845
  total_bytes: 3845
}

2021-05-28 00:14:05,598 INFO    MainThread:23026 [wandb_run.py:_wait_for_finish():1657] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 3845
  total_bytes: 3845
}

2021-05-28 00:14:05,699 INFO    MainThread:23026 [wandb_run.py:_wait_for_finish():1657] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 3845
  total_bytes: 3845
}

2021-05-28 00:14:05,800 INFO    MainThread:23026 [wandb_run.py:_wait_for_finish():1657] got exit ret: done: true
exit_result {
}
file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 3845
  total_bytes: 3845
}

2021-05-28 00:14:06,875 INFO    MainThread:23026 [wandb_run.py:_show_files():1879] logging synced files
