2021-05-28 05:05:56,902 INFO    MainThread:29752 [wandb_setup.py:_flush():69] setting env: {}
2021-05-28 05:05:56,902 INFO    MainThread:29752 [wandb_setup.py:_flush():69] setting login settings: {}
2021-05-28 05:05:56,902 INFO    MainThread:29752 [wandb_init.py:_log_setup():336] Logging user logs to /opt/ml/gitclone/p4-mod-model_diet/wandb/run-20210528_050556-sw3ialnt/logs/debug.log
2021-05-28 05:05:56,903 INFO    MainThread:29752 [wandb_init.py:_log_setup():337] Logging internal logs to /opt/ml/gitclone/p4-mod-model_diet/wandb/run-20210528_050556-sw3ialnt/logs/debug-internal.log
2021-05-28 05:05:56,903 INFO    MainThread:29752 [wandb_init.py:init():369] calling init triggers
2021-05-28 05:05:56,903 INFO    MainThread:29752 [wandb_init.py:init():374] wandb.init called with sweep_config: {}
config: {'img_size': 384, 'batch_size': 16, 'init_lr': 0.00043564753541279065}
2021-05-28 05:05:56,903 INFO    MainThread:29752 [wandb_init.py:init():389] re-initializing run, found existing run on stack: 3q0ojjik
2021-05-28 05:05:56,903 INFO    MainThread:29752 [wandb_run.py:finish():1208] finishing run seokjin/optuna/3q0ojjik
2021-05-28 05:05:56,903 INFO    MainThread:29752 [wandb_run.py:_atexit_cleanup():1535] got exitcode: 0
2021-05-28 05:05:56,903 INFO    MainThread:29752 [wandb_run.py:_restore():1507] restore
2021-05-28 05:05:58,911 INFO    MainThread:29752 [wandb_run.py:_wait_for_finish():1657] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 717
  total_bytes: 717
}

2021-05-28 05:05:59,175 INFO    MainThread:29752 [wandb_run.py:_wait_for_finish():1657] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 717
  total_bytes: 717
}

2021-05-28 05:05:59,563 INFO    MainThread:29752 [wandb_run.py:_wait_for_finish():1657] got exit ret: file_counts {
  wandb_count: 4
}
pusher_stats {
  uploaded_bytes: 717
  total_bytes: 3849
}

2021-05-28 05:05:59,964 INFO    MainThread:29752 [wandb_run.py:_wait_for_finish():1657] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 4045
  total_bytes: 4045
}

2021-05-28 05:06:00,066 INFO    MainThread:29752 [wandb_run.py:_wait_for_finish():1657] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 4045
  total_bytes: 4045
}

2021-05-28 05:06:00,168 INFO    MainThread:29752 [wandb_run.py:_wait_for_finish():1657] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 4045
  total_bytes: 4045
}

2021-05-28 05:06:00,269 INFO    MainThread:29752 [wandb_run.py:_wait_for_finish():1657] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 4045
  total_bytes: 4045
}

2021-05-28 05:06:00,371 INFO    MainThread:29752 [wandb_run.py:_wait_for_finish():1657] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 4045
  total_bytes: 4045
}

2021-05-28 05:06:00,473 INFO    MainThread:29752 [wandb_run.py:_wait_for_finish():1657] got exit ret: done: true
exit_result {
}
file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 4045
  total_bytes: 4045
}

2021-05-28 05:06:01,567 INFO    MainThread:29752 [wandb_run.py:_show_summary():1812] rendering summary
2021-05-28 05:06:01,568 INFO    MainThread:29752 [wandb_run.py:_show_history():1850] rendering history
2021-05-28 05:06:01,568 INFO    MainThread:29752 [wandb_run.py:_show_files():1879] logging synced files
2021-05-28 05:06:01,571 INFO    MainThread:29752 [wandb_init.py:init():418] starting backend
2021-05-28 05:06:01,571 INFO    MainThread:29752 [backend.py:_multiprocessing_setup():70] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2021-05-28 05:06:01,574 INFO    MainThread:29752 [backend.py:ensure_launched():132] starting backend process...
2021-05-28 05:06:01,621 INFO    MainThread:29752 [backend.py:ensure_launched():136] started backend process with pid: 30242
2021-05-28 05:06:01,623 INFO    MainThread:29752 [wandb_init.py:init():423] backend started and connected
2021-05-28 05:06:01,625 INFO    MainThread:29752 [wandb_init.py:init():465] updated telemetry
2021-05-28 05:06:01,626 INFO    MainThread:29752 [wandb_init.py:init():484] communicating current version
2021-05-28 05:06:02,500 INFO    MainThread:29752 [wandb_init.py:init():489] got version response upgrade_message: "wandb version 0.10.31 is available!  To upgrade, please run:\n $ pip install wandb --upgrade"

2021-05-28 05:06:02,500 INFO    MainThread:29752 [wandb_init.py:init():497] communicating run to backend with 30 second timeout
2021-05-28 05:06:02,737 INFO    MainThread:29752 [wandb_init.py:init():522] starting run threads in backend
2021-05-28 05:06:02,779 INFO    MainThread:29752 [wandb_run.py:_console_start():1565] atexit reg
2021-05-28 05:06:02,779 INFO    MainThread:29752 [wandb_run.py:_redirect():1412] redirect: SettingsConsole.REDIRECT
2021-05-28 05:06:02,779 INFO    MainThread:29752 [wandb_run.py:_redirect():1417] Redirecting console.
2021-05-28 05:06:02,780 INFO    MainThread:29752 [wandb_run.py:_redirect():1479] Redirects installed.
2021-05-28 05:06:02,780 INFO    MainThread:29752 [wandb_init.py:init():546] run started, returning control to user process
2021-05-28 05:20:49,180 INFO    MainThread:29752 [wandb_setup.py:_flush():69] setting env: {}
2021-05-28 05:20:49,180 INFO    MainThread:29752 [wandb_setup.py:_flush():69] setting login settings: {}
2021-05-28 05:20:49,180 INFO    MainThread:29752 [wandb_init.py:_log_setup():336] Logging user logs to /opt/ml/gitclone/p4-mod-model_diet/wandb/run-20210528_052049-361wor0v/logs/debug.log
2021-05-28 05:20:49,180 INFO    MainThread:29752 [wandb_init.py:_log_setup():337] Logging internal logs to /opt/ml/gitclone/p4-mod-model_diet/wandb/run-20210528_052049-361wor0v/logs/debug-internal.log
2021-05-28 05:20:49,181 INFO    MainThread:29752 [wandb_init.py:init():369] calling init triggers
2021-05-28 05:20:49,181 INFO    MainThread:29752 [wandb_init.py:init():374] wandb.init called with sweep_config: {}
config: {'img_size': 320, 'batch_size': 16, 'init_lr': 0.005896061335076594}
2021-05-28 05:20:49,181 INFO    MainThread:29752 [wandb_init.py:init():389] re-initializing run, found existing run on stack: sw3ialnt
2021-05-28 05:20:49,181 INFO    MainThread:29752 [wandb_run.py:finish():1208] finishing run seokjin/optuna/sw3ialnt
