2021-05-28 08:04:09,264 INFO    MainThread:29752 [wandb_setup.py:_flush():69] setting env: {}
2021-05-28 08:04:09,264 INFO    MainThread:29752 [wandb_setup.py:_flush():69] setting login settings: {}
2021-05-28 08:04:09,264 INFO    MainThread:29752 [wandb_init.py:_log_setup():336] Logging user logs to /opt/ml/gitclone/p4-mod-model_diet/wandb/run-20210528_080409-3f2w9oth/logs/debug.log
2021-05-28 08:04:09,264 INFO    MainThread:29752 [wandb_init.py:_log_setup():337] Logging internal logs to /opt/ml/gitclone/p4-mod-model_diet/wandb/run-20210528_080409-3f2w9oth/logs/debug-internal.log
2021-05-28 08:04:09,264 INFO    MainThread:29752 [wandb_init.py:init():369] calling init triggers
2021-05-28 08:04:09,264 INFO    MainThread:29752 [wandb_init.py:init():374] wandb.init called with sweep_config: {}
config: {'img_size': 160, 'batch_size': 64, 'init_lr': 0.0007005422912392361}
2021-05-28 08:04:09,264 INFO    MainThread:29752 [wandb_init.py:init():389] re-initializing run, found existing run on stack: 3b5kk0ka
2021-05-28 08:04:09,264 INFO    MainThread:29752 [wandb_run.py:finish():1208] finishing run seokjin/optuna/3b5kk0ka
2021-05-28 08:04:09,264 INFO    MainThread:29752 [wandb_run.py:_atexit_cleanup():1535] got exitcode: 0
2021-05-28 08:04:09,265 INFO    MainThread:29752 [wandb_run.py:_restore():1507] restore
2021-05-28 08:04:11,272 INFO    MainThread:29752 [wandb_run.py:_wait_for_finish():1657] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 717
  total_bytes: 717
}

2021-05-28 08:04:11,487 INFO    MainThread:29752 [wandb_run.py:_wait_for_finish():1657] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 717
  total_bytes: 717
}

2021-05-28 08:04:12,363 INFO    MainThread:29752 [wandb_run.py:_wait_for_finish():1657] got exit ret: file_counts {
  wandb_count: 3
}
pusher_stats {
  uploaded_bytes: 717
  total_bytes: 3596
}

2021-05-28 08:04:12,994 INFO    MainThread:29752 [wandb_run.py:_wait_for_finish():1657] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 4225
  total_bytes: 4225
}

2021-05-28 08:04:13,096 INFO    MainThread:29752 [wandb_run.py:_wait_for_finish():1657] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 4225
  total_bytes: 4225
}

2021-05-28 08:04:13,198 INFO    MainThread:29752 [wandb_run.py:_wait_for_finish():1657] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 4225
  total_bytes: 4225
}

2021-05-28 08:04:13,300 INFO    MainThread:29752 [wandb_run.py:_wait_for_finish():1657] got exit ret: done: true
exit_result {
}
file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 4225
  total_bytes: 4225
}

2021-05-28 08:04:14,408 INFO    MainThread:29752 [wandb_run.py:_show_summary():1812] rendering summary
2021-05-28 08:04:14,410 INFO    MainThread:29752 [wandb_run.py:_show_history():1850] rendering history
2021-05-28 08:04:14,411 INFO    MainThread:29752 [wandb_run.py:_show_files():1879] logging synced files
2021-05-28 08:04:14,413 INFO    MainThread:29752 [wandb_init.py:init():418] starting backend
2021-05-28 08:04:14,413 INFO    MainThread:29752 [backend.py:_multiprocessing_setup():70] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2021-05-28 08:04:14,416 INFO    MainThread:29752 [backend.py:ensure_launched():132] starting backend process...
2021-05-28 08:04:14,461 INFO    MainThread:29752 [backend.py:ensure_launched():136] started backend process with pid: 1404
2021-05-28 08:04:14,462 INFO    MainThread:29752 [wandb_init.py:init():423] backend started and connected
2021-05-28 08:04:14,464 INFO    MainThread:29752 [wandb_init.py:init():465] updated telemetry
2021-05-28 08:04:14,465 INFO    MainThread:29752 [wandb_init.py:init():484] communicating current version
2021-05-28 08:04:15,229 INFO    MainThread:29752 [wandb_init.py:init():489] got version response upgrade_message: "wandb version 0.10.31 is available!  To upgrade, please run:\n $ pip install wandb --upgrade"

2021-05-28 08:04:15,230 INFO    MainThread:29752 [wandb_init.py:init():497] communicating run to backend with 30 second timeout
2021-05-28 08:04:15,472 INFO    MainThread:29752 [wandb_init.py:init():522] starting run threads in backend
2021-05-28 08:04:15,511 INFO    MainThread:29752 [wandb_run.py:_console_start():1565] atexit reg
2021-05-28 08:04:15,512 INFO    MainThread:29752 [wandb_run.py:_redirect():1412] redirect: SettingsConsole.REDIRECT
2021-05-28 08:04:15,512 INFO    MainThread:29752 [wandb_run.py:_redirect():1417] Redirecting console.
2021-05-28 08:04:15,513 INFO    MainThread:29752 [wandb_run.py:_redirect():1479] Redirects installed.
2021-05-28 08:04:15,513 INFO    MainThread:29752 [wandb_init.py:init():546] run started, returning control to user process
2021-05-28 08:14:19,941 INFO    MainThread:29752 [wandb_setup.py:_flush():69] setting env: {}
2021-05-28 08:14:19,941 INFO    MainThread:29752 [wandb_setup.py:_flush():69] setting login settings: {}
2021-05-28 08:14:19,941 INFO    MainThread:29752 [wandb_init.py:_log_setup():336] Logging user logs to /opt/ml/gitclone/p4-mod-model_diet/wandb/run-20210528_081419-anh0hnpw/logs/debug.log
2021-05-28 08:14:19,941 INFO    MainThread:29752 [wandb_init.py:_log_setup():337] Logging internal logs to /opt/ml/gitclone/p4-mod-model_diet/wandb/run-20210528_081419-anh0hnpw/logs/debug-internal.log
2021-05-28 08:14:19,941 INFO    MainThread:29752 [wandb_init.py:init():369] calling init triggers
2021-05-28 08:14:19,941 INFO    MainThread:29752 [wandb_init.py:init():374] wandb.init called with sweep_config: {}
config: {'img_size': 256, 'batch_size': 64, 'init_lr': 0.0008153509777985978}
2021-05-28 08:14:19,941 INFO    MainThread:29752 [wandb_init.py:init():389] re-initializing run, found existing run on stack: 3f2w9oth
2021-05-28 08:14:19,941 INFO    MainThread:29752 [wandb_run.py:finish():1208] finishing run seokjin/optuna/3f2w9oth
